---
- name: Install lighttpd
  apt:
    pkg:
      - lighttpd

- include_tasks:
    file: lighttpd-write-config.yml
    apply:
      tags:
        - server

- name: Create lighttpd password file
  file:
    state: touch
    path: '{{ lighttpd_passwd_file }}'
    owner: root
    group: '{{ lighttpd_group }}'
    mode: '0640'

- name: Generate dhparam (this can take hours)
  command:
    cmd: 'openssl dhparam -out {{ dhparam_file }} 4096'
    creates: '{{ dhparam_file }}'

- name: Restart lighttpd
  service:
    name: lighttpd
    state: restarted
