---
- apt_key:
    id: '{{ letsencrypt_key }}'
    keyserver: keyserver.ubuntu.com

- apt_repository:
    repo: ppa:certbot/certbot

- shell:
    cmd: apt-key list 2>/dev/null | grep -c '^uid.*certbot'
  register: certbot_count
  changed_when: false

- assert:
    that:
      - (certbot_count.stdout | int) == 1

- shell:
    cmd: >
      apt-key list 2>/dev/null
      | grep -B1 '^uid.*certbot'
      | head -n 1
      | tr -d ' '
  register: observed_key
  changed_when: false

- assert:
    that:
      - observed_key.stdout == letsencrypt_key

- apt:
    update_cache: true
    pkg:
      - certbot

- set_fact:
    letsencrypt_cmd: >-
      certbot certonly -n --webroot -w {{ lighttpd_webroot }}
      --agree-tos --email 'haas.josh.a@gmail.com'
      {{ letsencrypt.domains | map('regex_replace', '^(.*)$', '-d \1') | join(' ') }}

- command:
    cmd: '{{ letsencrypt_cmd }}'

- template:
    src: lets-renew.j2
    dest: '{{ cron_dir }}/lets-renew'
    owner: root
    group: root
    mode: '0744'
    lstrip_blocks: true

- command:
    cmd: '{{ cron_dir }}/lets-renew'

- cron:
    name: lets-renew
    job: '{{ cron_dir }}/lets-renew &> /dev/null'
    day: '1'
    hour: '4'

- include_tasks:
    file: lighttpd-write-config.yml
    apply:
      tags:
        - server
  vars:
    letsencrypt_done: true

- service:
    name: lighttpd
    state: restarted
