---
- name: Install pelican
  pip:
    name:
      - pelican[Markdown]

- name: Install pelican themes
  git:
    repo: https://github.com/getpelican/pelican-themes.git
    dest: '{{ pelican_themes_dir }}'

- name: Compose pelican dir
  set_fact:
    pelican_dir: '{{ (("" if pelican_rel[0] == "/" else lighttpd_webroot + "/") + pelican_rel) | dirname }}'
  vars:
    pelican_rel: '{{ lighttpd.domains[pelican.domain].root }}'
