---
- name: Generate lighttpd config
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: '{{ lighttpd_group }}'
    mode: '0640'
    lstrip_blocks: True
