---
- name: Install utilities
  apt:
    pkg:
      - aptitude
      - curl
      - dnsutils
      - htop
      - iftop
      - iotop
      - iperf3
      - jq
      - mediainfo
      - ncdu
      - netcat
      - nmap
