---
- name: Install pip3
  apt:
    pkg:
      - python3-pip

- name: Install python libraries
  pip:
    name:
      - lxml
      - Pillow
      - pytz
      - requests
      - speedtest-cli
      - youtube-dl
