---
- apt:
    state: present
    pkg:
      - openssh-server

- lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.key }}'
    line: '{{ item.value }}'
  with_dict:
    '^#?PermitRootLogin': 'PermitRootLogin no'
    '^#?PasswordAuthentication': 'PasswordAuthentication no'

- service:
    name: sshd
    state: restarted

- file:
    state: directory
    path: ~/.ssh
    mode: '0700'
  become: no

- copy:
    src: '{{ ssh_auth_keys }}'
    dest: ~/.ssh/authorized_keys
    mode: '0600'
  become: no
