---
- name: Install SSH server
  apt:
    state: present
    pkg:
      - openssh-server

- name: Harden SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.key }}'
    line: '{{ item.value }}'
  with_dict:
    '^#?PermitRootLogin': 'PermitRootLogin no'
    '^#?PasswordAuthentication': 'PasswordAuthentication no'

- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Create ~/.ssh dir
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'
  become: no

- name: Copy authorized_keys
  copy:
    src: '{{ ssh_auth_keys }}'
    dest: ~/.ssh/authorized_keys
    mode: '0600'
  become: no
